### ISSUE TITLE
Suggestion: Put all config files in root rather than .config/nvim

### ISSUE THREAD

**Issue by megadrive** [frans-johansson/lazy-nvim-starter#1]
My use case for this is that I will git clone the root files. As it is, I have to clone into a separate directory and then move those files into my own .config folder.

Having the files be moved from `/.config/nvim` to `/` makes it so i can clone or `degit` into my own ~/.config/nvim folder and modify from there.

**Comment by ForeverZer0** [comment]
I agree this would be a minor improvement, and make it far more flexible. Users could just specify their own directory with the git command as is typical:

```
git clone git@github.com:frans-johansson/lazy-nvim-starter.git ~/.config/nvim
```

Being nested within a directory structure relative to the `$HOME` directory pretty much guarantees that most users are forced to do the 2-step clone/move. While it is only a very minor inconvenience, it is rather unconventional.

**Comment by connorjs** [comment]
> pretty much guarantees that most users are forced to do the 2-step clone/move

Maybe we should update the README to include the other `stow` flags: `stow -vt $HOME .` (where `-v` is verbose and prints what was done)

> This assumes you have cloned this repository to your home directory, otherwise you will have to supply stow with some more flags

---

Here’s what I did to test out this starter project.

```shell
mkdir -p ~/w/mkdir frans-johansson
cd ~/w/frans-johansson
git clone git@github.com:frans-johansson/lazy-nvim-starter.git
cd lazy-nvim-starter
stow -vt $HOME .

# LINK: .config/nvim/init.lua => ../../w/frans-johansson/lazy-nvim-starter/.config/nvim/init.lua
# LINK: .config/nvim/lua => ../../w/frans-johansson/lazy-nvim-starter/.config/nvim/lua
```

So, I prefer the current structure. (It also simplifies moving it into your own dotfiles repo.)

`brew install stow` if you don’t have stow and use homebrew

**Comment by frans-johansson** [comment]
Hello everyone! Sorry for the complete radio-silence on my end, I guess I never really anticipated people engaging with this little starter repo 😅 Regarding the way I decided to structure this repo, the whole point was to make it simple to include in your personal dotfiles repos.

I like the idea @connorjs suggested though, modifying the README slightly to clarify how `stow` functions in the context of this repo. I'll go ahead and push an update in a little bit, but seeing as I will not update the structure of the repo, I'll go ahead and close this issue for now.
